% Problem 2: Even Fibonacci numbers
%--------------------------------------------------------------------
% Each new term in the Fibonacci sequence is generated by adding the
% previous two terms. By starting with 1, and 2, the first 10 terms
% will be:
%   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
%
% By considering the terms in the Fibonacci sequence whose values do
% not exceed four million, find the sum of the even-valued terms.
%--------------------------------------------------------------------
sum_even_fib(Limit, Sum):-
    sum_fib(1, 1, Limit, Sum).

sum_fib(_, Second, Limit, 0):-
    Second >= Limit.
sum_fib(First, Second, Limit, Sum):-
    Current is First + Second,
    Current mod 2 =:= 0,
    sum_fib(Second, Current, Limit, SubSum), !,
    Sum is Current + SubSum.
sum_fib(First, Second, Limit, Sum):-
    Current is First + Second,
    sum_fib(Second, Current, Limit, Sum), !.

% ?- sum_even_fib(4000000, Sum).
% Sum = 4613732.
